### PR TITLE
inbox: distinguish new mail action: *New

### PR DESCRIPTION
**Pull request by ArneBab**
a tiny change I forgot to push. Despite how simple it is, it helps my workflow a lot.

### CODE REVIEW

**Comment by Thynix** [comment]
I'm missing something. What's the reasoning for this?

**Comment by ArneBab** [comment]
The reasoning is that I stumbled repeatedly over not realizing that I can just click [New] to send a new mail. With [*New] that does not happen (it’s clearly visible that this isn’t a folder). This builds on a change (which did not show up in the pull-request so I assume it is already merged) which adds the [New] link to the list of folders.

This is relevant when the menu is folded or on top, so that there’s no directly clickable link for creating a new message.

**Comment by Thynix** [comment]
What about bolding this or doing something outside the string? Putting it in the string makes for more translation work. It's already likely to be unclear for translators whether this is "new" the description or "new" the action.

**Comment by ArneBab** [comment]
I think anything which makes it stand out is a good idea. I think bolding should work. I’m not sure whether the * would work in all translations. If it would, I could also simply port the change to all the translations myself (adding a star for each of them isn’t that much work for me).

I did not think about the translation work when doing the change (sorry for that).

**Comment by ArneBab** [comment]
Close as "wrong approach".

**Pull request closed without merging**
