### PR TITLE
Add web of trust link to web interface

### PR DESCRIPTION
**Pull request by Bombe**
This adds a link to the web of trust profile of a sender in the message list in the web interface.

### CODE REVIEW

**Comment by Thynix** [comment]
Looks good! Thanks for writing this! My minor gripe is that under the [commit message standards](https://wiki.freenetproject.org/Coding_standards#Commit_Messages) summary lines should not end with a full stop. Would you like me to merge this anyway? I'm also willing to fix it for you.

**Comment by Bombe** [comment]
No, I’ll take care of that. It is however the most unusual part of our coding standards. :)

**Comment by Thynix** [comment]
Oh, I didn't realize.

**Comment by Bombe** [comment]
Not a biggy, I just need to remind myself of that when creating Freenet-related commits. :)

**Pull request merged**
